services:
  - type: web
    name: flask-audio-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
  - type: worker
    name: radio-worker
    env: python
    startCommand: python radio_worker.py
